# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_monsterlm_wrappers", use_symbols = TRUE, package_name = "monsterlm")

#' @docType package
#' @usage NULL
#' @useDynLib monsterlm, .registration = TRUE
NULL

#' @export
monsterlm <- function(dir, env_type) .Call(wrap__monsterlm, dir, env_type)

#' @export
plink_qc <- function(plink, out_dir, get_genotype, get_allele, maf) .Call(wrap__plink_qc, plink, out_dir, get_genotype, get_allele, maf)


# nolint end
